"""wallet module final

Revision ID: b0ed51573b3d
Revises: 79c57b5fc483
Create Date: 2026-06-06 11:03:30.330414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0ed51573b3d'
down_revision: Union[str, Sequence[str], None] = '79c57b5fc483'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_banners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('redirect_url', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_banners_id'), 'game_banners', ['id'], unique=False)
    op.create_table('game_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=True),
    sa.Column('default_currency', sa.String(length=10), nullable=True),
    sa.Column('min_deposit', sa.Float(), nullable=True),
    sa.Column('max_deposit', sa.Float(), nullable=True),
    sa.Column('default_commission', sa.Float(), nullable=True),
    sa.Column('default_rtp', sa.Float(), nullable=True),
    sa.Column('allowed_countries', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_settings_id'), 'game_settings', ['id'], unique=False)
    op.create_table('payment_gateway',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('secret_key', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_payment_gateway_id'), 'payment_gateway', ['id'], unique=False)
    op.create_table('webhook_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gateway_name', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_log_id'), 'webhook_log', ['id'], unique=False)
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_number', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_id'), 'ticket', ['id'], unique=False)
    op.create_index(op.f('ix_ticket_ticket_number'), 'ticket', ['ticket_number'], unique=True)
    op.create_index(op.f('ix_ticket_user_id'), 'ticket', ['user_id'], unique=False)
    op.create_table('wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('deposit_balance', sa.Float(), nullable=True),
    sa.Column('winning_balance', sa.Float(), nullable=True),
    sa.Column('bonus_balance', sa.Float(), nullable=True),
    sa.Column('locked_balance', sa.Float(), nullable=True),
    sa.Column('total_deposited', sa.Float(), nullable=True),
    sa.Column('total_withdrawn', sa.Float(), nullable=True),
    sa.Column('total_won', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_id'), 'wallet', ['id'], unique=False)
    op.create_index(op.f('ix_wallet_user_id'), 'wallet', ['user_id'], unique=True)
    op.create_table('wallet_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('old_balance', sa.Float(), nullable=False),
    sa.Column('new_balance', sa.Float(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_audit_logs_admin_id'), 'wallet_audit_logs', ['admin_id'], unique=False)
    op.create_index(op.f('ix_wallet_audit_logs_id'), 'wallet_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_wallet_audit_logs_user_id'), 'wallet_audit_logs', ['user_id'], unique=False)
    op.create_table('wallet_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('opening_balance', sa.Float(), nullable=False),
    sa.Column('closing_balance', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('reference_type', sa.String(), nullable=True),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_transactions_id'), 'wallet_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_transaction_id'), 'wallet_transactions', ['transaction_id'], unique=True)
    op.create_index(op.f('ix_wallet_transactions_user_id'), 'wallet_transactions', ['user_id'], unique=False)
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=False),
    sa.Column('prize_amount', sa.Float(), nullable=False),
    sa.Column('settlement_status', sa.String(), nullable=True),
    sa.Column('declared_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_result_game_id'), 'result', ['game_id'], unique=False)
    op.create_index(op.f('ix_result_id'), 'result', ['id'], unique=False)
    op.create_index(op.f('ix_result_winner_id'), 'result', ['winner_id'], unique=False)
    op.add_column('deposits', sa.Column('gateway_transaction_id', sa.String(), nullable=True))
    op.alter_column('deposits', 'amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('deposits', 'gateway',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('deposits', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('deposits', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.drop_index(op.f('ix_deposits_gateway_tx_id'), table_name='deposits')
    op.drop_index(op.f('ix_deposits_status'), table_name='deposits')
    op.create_unique_constraint(None, 'deposits', ['gateway_transaction_id'])
    op.drop_constraint(op.f('deposits_user_id_fkey'), 'deposits', type_='foreignkey')
    op.create_foreign_key(None, 'deposits', 'user', ['user_id'], ['id'])
    op.drop_column('deposits', 'updated_at')
    op.drop_column('deposits', 'gateway_tx_id')
    op.drop_column('deposits', 'payload')
    op.alter_column('game_categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('game_categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('game_categories_name_key'), 'game_categories', type_='unique')
    op.create_index(op.f('ix_game_categories_name'), 'game_categories', ['name'], unique=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'mobile',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_users_mobile'), table_name='users')
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_constraint(op.f('users_vip_level_id_fkey'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('users_referrer_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'referral_code')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'referrer_id')
    op.drop_column('users', 'is_locked')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'vip_level_id')
    op.add_column('withdrawals', sa.Column('bank_name', sa.String(), nullable=True))
    op.add_column('withdrawals', sa.Column('account_number', sa.String(), nullable=True))
    op.add_column('withdrawals', sa.Column('upi_id', sa.String(), nullable=True))
    op.add_column('withdrawals', sa.Column('approved_by', sa.Integer(), nullable=True))
    op.alter_column('withdrawals', 'amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('withdrawals', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('withdrawals', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.drop_index(op.f('ix_withdrawals_status'), table_name='withdrawals')
    op.drop_constraint(op.f('withdrawals_user_id_fkey'), 'withdrawals', type_='foreignkey')
    op.drop_constraint(op.f('withdrawals_bank_account_id_fkey'), 'withdrawals', type_='foreignkey')
    op.create_foreign_key(None, 'withdrawals', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'withdrawals', 'users', ['approved_by'], ['id'])
    op.drop_column('withdrawals', 'processed_at')
    op.drop_column('withdrawals', 'updated_at')
    op.drop_column('withdrawals', 'bank_account_id')
    op.drop_column('withdrawals', 'rejection_reason')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('withdrawals', sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('withdrawals', sa.Column('bank_account_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('withdrawals', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('withdrawals', sa.Column('processed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'withdrawals', type_='foreignkey')
    op.drop_constraint(None, 'withdrawals', type_='foreignkey')
    op.create_foreign_key(op.f('withdrawals_bank_account_id_fkey'), 'withdrawals', 'bank_accounts', ['bank_account_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('withdrawals_user_id_fkey'), 'withdrawals', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_withdrawals_status'), 'withdrawals', ['status'], unique=False)
    op.alter_column('withdrawals', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('withdrawals', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('withdrawals', 'amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)
    op.drop_column('withdrawals', 'approved_by')
    op.drop_column('withdrawals', 'upi_id')
    op.drop_column('withdrawals', 'account_number')
    op.drop_column('withdrawals', 'bank_name')
    op.add_column('users', sa.Column('vip_level_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('failed_login_attempts', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_locked', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('referrer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('locked_until', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('referral_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('users_referrer_id_fkey'), 'users', 'users', ['referrer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('users_vip_level_id_fkey'), 'users', 'vip_levels', ['vip_level_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    op.create_index(op.f('ix_users_mobile'), 'users', ['mobile'], unique=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('users', 'mobile',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_index(op.f('ix_game_categories_name'), table_name='game_categories')
    op.create_unique_constraint(op.f('game_categories_name_key'), 'game_categories', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('game_categories', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('game_categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('deposits', sa.Column('payload', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('deposits', sa.Column('gateway_tx_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('deposits', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'deposits', type_='foreignkey')
    op.create_foreign_key(op.f('deposits_user_id_fkey'), 'deposits', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'deposits', type_='unique')
    op.create_index(op.f('ix_deposits_status'), 'deposits', ['status'], unique=False)
    op.create_index(op.f('ix_deposits_gateway_tx_id'), 'deposits', ['gateway_tx_id'], unique=True)
    op.alter_column('deposits', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('deposits', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('deposits', 'gateway',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('deposits', 'amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)
    op.drop_column('deposits', 'gateway_transaction_id')
    op.drop_index(op.f('ix_result_winner_id'), table_name='result')
    op.drop_index(op.f('ix_result_id'), table_name='result')
    op.drop_index(op.f('ix_result_game_id'), table_name='result')
    op.drop_table('result')
    op.drop_index(op.f('ix_wallet_transactions_user_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_transaction_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_id'), table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_index(op.f('ix_wallet_audit_logs_user_id'), table_name='wallet_audit_logs')
    op.drop_index(op.f('ix_wallet_audit_logs_id'), table_name='wallet_audit_logs')
    op.drop_index(op.f('ix_wallet_audit_logs_admin_id'), table_name='wallet_audit_logs')
    op.drop_table('wallet_audit_logs')
    op.drop_index(op.f('ix_wallet_user_id'), table_name='wallet')
    op.drop_index(op.f('ix_wallet_id'), table_name='wallet')
    op.drop_table('wallet')
    op.drop_index(op.f('ix_ticket_user_id'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_ticket_number'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_id'), table_name='ticket')
    op.drop_table('ticket')
    op.drop_index(op.f('ix_webhook_log_id'), table_name='webhook_log')
    op.drop_table('webhook_log')
    op.drop_index(op.f('ix_payment_gateway_id'), table_name='payment_gateway')
    op.drop_table('payment_gateway')
    op.drop_index(op.f('ix_game_settings_id'), table_name='game_settings')
    op.drop_table('game_settings')
    op.drop_index(op.f('ix_game_banners_id'), table_name='game_banners')
    op.drop_table('game_banners')
    # ### end Alembic commands ###
